name:                git-slides
version:             0.1.0.0
github:              "gelisam/rerec"
license:             PublicDomain
author:              "Samuel Gélineau"
maintainer:          "gelisam@gmail.com"

#extra-source-files:
#- README.md
#- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/gelisam/rerec#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- filepath
- gitlib
- lens
- lifted-async
- monad-control
- tagged
- text
- transformers

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  git-slides:
    main:                main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - git-slides
